name = "mastra-finance-home-ai"
main = "src/index.ts"
compatibility_date = "2024-12-01"

# Vectorize binding for finance transaction embeddings
[[vectorize]]
binding = "FINANCE_VECTORS"
index_name = "finance-transactions"

# Environment variables
[vars]
ENVIRONMENT = "development" 